//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zxcvbn.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zxcvbn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   centuries に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Centuries {
            get {
                return ResourceManager.GetString("Centuries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   days に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   you
        ///i
        ///the
        ///to
        ///a
        ///&apos;s
        ///it
        ///and
        ///that
        ///&apos;t
        ///of
        ///is
        ///in
        ///what
        ///we
        ///me
        ///this
        ///he
        ///for
        ///my
        ///on
        ///have
        ///your
        ///do
        ///was
        ///&apos;m
        ///no
        ///not
        ///be
        ///are
        ///don
        ///&apos;re
        ///know
        ///can
        ///with
        ///but
        ///all
        ///so
        ///just
        ///there
        ///here
        ///they
        ///like
        ///&apos;ll
        ///get
        ///she
        ///go
        ///if
        ///right
        ///out
        ///about
        ///up
        ///at
        ///him
        ///now
        ///oh
        ///one
        ///come
        ///well
        ///her
        ///how
        ///yeah
        ///&apos;ve
        ///will
        ///got
        ///want
        ///think
        ///as
        ///see
        ///did
        ///good
        ///who
        ///why
        ///from
        ///let
        ///his
        ///yes
        ///when
        ///going
        ///time
        ///an
        ///okay
        ///back
        ///look
        ///us
        ///would
        ///them
        ///where
        ///were
        ///take
        ///then
        ///had
        ///or
        ///been
        ///our
        ///gonna
        ///tell
        ///really
        ///man        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mary
        ///patricia
        ///linda
        ///barbara
        ///elizabeth
        ///jennifer
        ///maria
        ///susan
        ///margaret
        ///dorothy
        ///lisa
        ///nancy
        ///karen
        ///betty
        ///helen
        ///sandra
        ///donna
        ///carol
        ///ruth
        ///sharon
        ///michelle
        ///laura
        ///sarah
        ///kimberly
        ///deborah
        ///jessica
        ///shirley
        ///cynthia
        ///angela
        ///melissa
        ///brenda
        ///amy
        ///anna
        ///rebecca
        ///virginia
        ///kathleen
        ///pamela
        ///martha
        ///debra
        ///amanda
        ///stephanie
        ///carolyn
        ///christine
        ///marie
        ///janet
        ///catherine
        ///frances
        ///ann
        ///joyce
        ///diane
        ///alice
        ///julie
        ///heather
        ///teresa
        ///doris
        ///gloria
        ///evelyn
        ///jean
        ///cheryl
        ///mildred
        ///katherine
        ///joan
        ///ashley
        ///judi [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FemaleNames {
            get {
                return ResourceManager.GetString("FemaleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   hours に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   instant に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Instant {
            get {
                return ResourceManager.GetString("Instant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   james
        ///john
        ///robert
        ///michael
        ///william
        ///david
        ///richard
        ///charles
        ///joseph
        ///thomas
        ///christopher
        ///daniel
        ///paul
        ///mark
        ///donald
        ///george
        ///kenneth
        ///steven
        ///edward
        ///brian
        ///ronald
        ///anthony
        ///kevin
        ///jason
        ///matthew
        ///gary
        ///timothy
        ///jose
        ///larry
        ///jeffrey
        ///frank
        ///scott
        ///eric
        ///stephen
        ///andrew
        ///raymond
        ///gregory
        ///joshua
        ///jerry
        ///dennis
        ///walter
        ///patrick
        ///peter
        ///harold
        ///douglas
        ///henry
        ///carl
        ///arthur
        ///ryan
        ///roger
        ///joe
        ///juan
        ///jack
        ///albert
        ///jonathan
        ///justin
        ///terry
        ///gerald
        ///keith
        ///samuel
        ///willie
        ///ralph
        ///lawrence
        ///nicholas
        ///roy
        ///benjamin [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MaleNames {
            get {
                return ResourceManager.GetString("MaleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   minutes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   months に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   123456
        ///123456789
        ///qwerty
        ///password
        ///111111
        ///12345678
        ///abc123
        ///1234567
        ///password1
        ///12345
        ///1234567890
        ///123123
        ///000000
        ///iloveyou
        ///1234
        ///1q2w3e4r5t
        ///qwertyuiop
        ///123
        ///monkey
        ///dragon
        ///123456a
        ///654321
        ///123321
        ///666666
        ///1qaz2wsx
        ///myspace1
        ///121212
        ///homelesspa
        ///123qwe
        ///a123456
        ///123abc
        ///1q2w3e4r
        ///qwe123
        ///7777777
        ///qwerty123
        ///target123
        ///tinkle
        ///987654321
        ///qwerty1
        ///222222
        ///zxcvbnm
        ///1g2w3e4r
        ///gwerty
        ///zag12wsx
        ///gwerty123
        ///555555
        ///fuckyou
        ///112233
        ///asdfghjkl
        ///1q2w3e
        ///123123123
        ///qazwsx
        ///computer
        ///princess
        ///12345a
        ///ashley
        ///159 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Passwords {
            get {
                return ResourceManager.GetString("Passwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   seconds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add another word or two. Uncommon words are better. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Suggestion_AddAnotherWordOrTwo {
            get {
                return ResourceManager.GetString("Suggestion.AddAnotherWordOrTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All-uppercase is almost as easy to guess as all-lowercase に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Suggestion_AllCapsEasy {
            get {
                return ResourceManager.GetString("Suggestion.AllCapsEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Avoid dates and years that are associated with you に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Suggestion_AvoidDatesYearsAssociatedYou {
            get {
                return ResourceManager.GetString("Suggestion.AvoidDatesYearsAssociatedYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Avoid repeated words and characters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Suggestion_AvoidRepeatedWordsAndChars {
            get {
                return ResourceManager.GetString("Suggestion.AvoidRepeatedWordsAndChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Avoid sequences に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Suggestion_AvoidSequences {
            get {
                return ResourceManager.GetString("Suggestion.AvoidSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Avoid recent years \n Avoid years that are associated with you に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Suggestion_AvoidYearsAssociatedYou {
            get {
                return ResourceManager.GetString("Suggestion.AvoidYearsAssociatedYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Capitalization doesn&apos;t help very much に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Suggestion_CapsDontHelp {
            get {
                return ResourceManager.GetString("Suggestion.CapsDontHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Suggestion_Empty {
            get {
                return ResourceManager.GetString("Suggestion.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Predictable substitutions like &apos;@&apos; instead of &apos;a&apos; don&apos;t help very much に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Suggestion_PredictableSubstitutionsEasy {
            get {
                return ResourceManager.GetString("Suggestion.PredictableSubstitutionsEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reversed words aren&apos;t much harder to guess に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Suggestion_ReversedWordEasy {
            get {
                return ResourceManager.GetString("Suggestion.ReversedWordEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use a longer keyboard pattern with more turns に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Suggestion_UseLongerKeyboardPattern {
            get {
                return ResourceManager.GetString("Suggestion.UseLongerKeyboardPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   smith
        ///johnson
        ///williams
        ///jones
        ///brown
        ///davis
        ///miller
        ///wilson
        ///moore
        ///taylor
        ///anderson
        ///thomas
        ///jackson
        ///white
        ///harris
        ///martin
        ///thompson
        ///garcia
        ///martinez
        ///robinson
        ///clark
        ///rodriguez
        ///lewis
        ///lee
        ///walker
        ///hall
        ///allen
        ///young
        ///hernandez
        ///king
        ///wright
        ///lopez
        ///hill
        ///scott
        ///green
        ///adams
        ///baker
        ///gonzalez
        ///nelson
        ///carter
        ///mitchell
        ///perez
        ///roberts
        ///turner
        ///phillips
        ///campbell
        ///parker
        ///evans
        ///edwards
        ///collins
        ///stewart
        ///sanchez
        ///morris
        ///rogers
        ///reed
        ///cook
        ///morgan
        ///bell
        ///murphy
        ///bailey
        ///rivera
        ///cooper
        ///richardson
        ///cox
        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Surnames {
            get {
                return ResourceManager.GetString("Surnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Common names and surnames are easy to guess に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Warning_CommonNameSurnamesEasy {
            get {
                return ResourceManager.GetString("Warning.CommonNameSurnamesEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is a very common password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Warning_CommonPasswords {
            get {
                return ResourceManager.GetString("Warning.CommonPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dates are often easy to guess に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Warning_DatesEasy {
            get {
                return ResourceManager.GetString("Warning.DatesEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Warning_Empty {
            get {
                return ResourceManager.GetString("Warning.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Names and surnames by themselves are easy to guess に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Warning_NameSurnamesEasy {
            get {
                return ResourceManager.GetString("Warning.NameSurnamesEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recent years are easy to guess に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Warning_RecentYearsEasy {
            get {
                return ResourceManager.GetString("Warning.RecentYearsEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repeats like &quot;aaa&quot; are easy to guess に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Warning_RepeatsLikeAaaEasy {
            get {
                return ResourceManager.GetString("Warning.RepeatsLikeAaaEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repeats like &quot;abcabcabc&quot; are only slightly harder to guess than &quot;abc&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Warning_RepeatsLikeAbcSlighterHarder {
            get {
                return ResourceManager.GetString("Warning.RepeatsLikeAbcSlighterHarder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sequences like abc or 6543 are easy to guess に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Warning_SequenceAbcEasy {
            get {
                return ResourceManager.GetString("Warning.SequenceAbcEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Short keyboard patterns are easy to guess に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Warning_ShortKeyboardPatterns {
            get {
                return ResourceManager.GetString("Warning.ShortKeyboardPatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is similar to a commonly used password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Warning_SimilarCommonPasswords {
            get {
                return ResourceManager.GetString("Warning.SimilarCommonPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Straight rows of keys are easy to guess に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Warning_StraightRow {
            get {
                return ResourceManager.GetString("Warning.StraightRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is a top-100 common password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Warning_Top100Passwords {
            get {
                return ResourceManager.GetString("Warning.Top100Passwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is a top-10 common password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Warning_Top10Passwords {
            get {
                return ResourceManager.GetString("Warning.Top10Passwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A word by itself is easy to guess に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Warning_WordEasy {
            get {
                return ResourceManager.GetString("Warning.WordEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   years に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
    }
}
